# Generated by Django 5.1.4 on 2025-01-05 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="product_images/")),
                ("description", models.TextField()),
                (
                    "farmer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("farmer_contact", models.CharField(max_length=15)),
                (
                    "date_of_posting",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
