# Generated by Django 5.1.4 on 2024-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0002_remove_cropprice_market_alter_cropprice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropprice',
            name='market',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='price',
            field=models.FloatField(),
        ),
    ]
