# Generated by Django 5.1.4 on 2024-12-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0003_cropprice_market_alter_cropprice_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhone',
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='market',
            field=models.CharField(default='Agmarknet', max_length=100),
        ),
    ]
