# Generated by Django 5.1.4 on 2024-12-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0004_delete_userphone_alter_cropprice_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='market',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cropprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
