# Generated by Django 5.1.4 on 2024-12-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TG', 'Telangana'), ('KL', 'Kerala')], max_length=2)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('commodity', 'state', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cropprice')),
            ],
            options={
                'unique_together': {('crop_price', 'predicted_date')},
            },
        ),
    ]
